version: '3.9'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: "nginx"
        volumes:
            - ./www:/var/www/html:ro
            - ./log/nginx:/var/log/nginx:consistent
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        depends_on:
            - php
            - mysql
        restart: always
    php:
        build: ./php
        image: php
        container_name: "php"
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - ./www:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
        restart: always
    mysql:
        image: mysql
        container_name: "mysql"
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
            - ./log/mysql:/var/log/mysql:consistent
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
        restart: always
volumes:
    mysql_data: